### ISSUE TITLE
有关训练时mask的使用

### ISSUE THREAD

**Issue by hannanyi** [htyjers/StrDiffusion#10]
您好！我想请问下，您在训练模型时采用的那种策略？mask是在整个数据集上训练好得到一个模型，测试时在不同孔洞率10-20%，20%-30%等等上进行测试；还是在不同孔洞率的mask直接训练，得到对应于不同孔洞率的模型，再分别测试

**Comment by htyjers** [comment]
将中高比例的mask混合在一起进行训练，然后在不同比例的mask上进行测试

**Comment by hannanyi** [comment]
好的明白了，谢谢你啊~
