### ISSUE TITLE
train time

### ISSUE THREAD

**Issue by maoqiuerer** [htyjers/StrDiffusion#11]
如果我想训练27000张图片，是不是会需要很多天，不知道多少张图片用来训练比较好？

**Comment by htyjers** [comment]
我采用的PSV数据集有14900张图片。所以我认为27000张图片，训练个差不多4-5天就可以了，如果你有多块GPU,我推荐是一块专门用于训练Texture Denoising Model，另一块可以先训练Structure Denoising Model，后训练Discriminator Network，并且可以调高这2个模型的batchsize,因为他们的参数量更少，训练可以更快。

**Comment by maoqiuerer** [comment]
![image](https://github.com/htyjers/StrDiffusion/assets/128476770/da2551ba-7397-43cc-899d-434e689b1d02)
![微信图片_20240428133517](https://github.com/htyjers/StrDiffusion/assets/128476770/d62ee35e-7f9a-4c4f-9394-d072b0ce2762)
我训练1万张图片，n改成了7百万，别的不变，已经超了内存，我应该减少数值还是图片数呀

**Comment by htyjers** [comment]
修改[batch_size](https://github.com/htyjers/StrDiffusion/blob/977cb8546a8f808a340cd071e63021c65351d1cc/train/texture/config/inpainting/options/train/ir-sde.yml#L26)小点就行
