### ISSUE TITLE
about test parameter and time

### ISSUE THREAD

**Issue by SouthCity** [htyjers/StrDiffusion#12]
Hello, thank you for your contribution. 
May I ask whether the parameter under sde in ir-sde.yml should follow the default T=100 or change T to 400 when testing? 
When changing to T=400, I found that it took several minutes to test one image. Is this normal?(Maybe it's because under windows)

**Comment by htyjers** [comment]
Thank you for your attention, it's normal that the T=400 need more time to test, please set the T with **different pretrained models**.
---For [Places2, T=400](https://pan.baidu.com/s/1vxZ57te6TratZwKsuUYV8Q?pwd=n8dr), you should set the **T=400** in ir-sde.yml 
---For [Places2, T=100](https://pan.baidu.com/s/1yw8lE3Vk_3IsR3HoVf84Ww?_at_=1713468801558#list/path=%2F), you should set the **T=100** in ir-sde.yml

**Comment by SouthCity** [comment]
> Thank you for your attention, it's normal that the T=400 need more time to test, please set the T with **different pretrained models**. ---For [Places2, T=400](https://pan.baidu.com/s/1vxZ57te6TratZwKsuUYV8Q?pwd=n8dr), you should set the **T=400** in ir-sde.yml ---For [Places2, T=100](https://pan.baidu.com/s/1yw8lE3Vk_3IsR3HoVf84Ww?_at_=1713468801558#list/path=%2F), you should set the **T=100** in ir-sde.yml

got it. thank you sir.
