### ISSUE TITLE
condition add

### ISSUE THREAD

**Issue by maoqiuerer** [htyjers/StrDiffusion#13]
如果我想添加一个条件特征比如canny、mask和输入一起嵌入进去，我需要修改输入维度和权重吗？

**Comment by htyjers** [comment]
你可以在[这里](https://github.com/htyjers/StrDiffusion/blob/977cb8546a8f808a340cd071e63021c65351d1cc/train/texture/config/inpainting/options/train/ir-sde.yml#L34-L40)对输入的维度进行更改，同时，你可以在[这里](https://github.com/htyjers/StrDiffusion/blob/977cb8546a8f808a340cd071e63021c65351d1cc/train/texture/config/inpainting/models/modules/DenoisingUNet_arch.py#L251)对模型代码进行更改。你需要观察训练过程和结果来判断是否需要改变权重
