### ISSUE TITLE
训练structure时终端没有过程记录，麻烦请教一下如何解决？

### ISSUE THREAD

**Issue by whuPanda123** [htyjers/StrDiffusion#15]
我用双卡TITAN V去训练structure模型，然后ir-sde.yml里gpu_ids改为了[0,1]，然后把tensorboard相关内容注释掉了，终端跑模型时发现在运行但是没有过程记录，也不知道什么时候完成。新手小白麻烦求赐教，不胜感激！
![Uploading 微信图片_20240520114422.png…]()

**Comment by htyjers** [comment]
在训练过程中，您可以检查看下train下面的文件夹下是否生成了一个experiments文件夹，按./experiments/inpainting/ir-sde路径点击进入,你会找到一个单独的log文件和4个文件夹，训练的过程记录保存在log文件中，训练的文件保存在models文件夹下面，我做了一个文件夹的示意图以供参考：
train
----structure
----experiments
------inpainting
--------ir-sde
----------**train_ir-sde_**********.log**
----------tb_logger
----------**models**
----------val_images
----------training_state

**Comment by whuPanda123** [comment]
很感谢您，我已经找到了实验记录路径，后续如果出现困难，希望可以继续与您交流！
![Uploading log.png…]()

**Comment by whuPanda123** [comment]
麻烦请教下您，您在4个NVIDIA 2080TI GPU上训练第一步structure的denoising model大概需要多久呢？我在2个TITAN V GPU上已经训练了28个小时，350个epoch还在训练中，想询问下是正常情况嘛？

**Comment by htyjers** [comment]
你可以在这里设置需要训练的总batch数，我之前是为Places2设置的，可能与你的训练数据集大小不匹配
https://github.com/htyjers/StrDiffusion/blob/5749a214bb39754be165fa2bf76f96f13bc3e4a3/train/structure/config/inpainting/options/train/ir-sde.yml#L55-L57
