### ISSUE TITLE
[Places2] T=100 model extraction cipher

### ISSUE THREAD

**Issue by lzwRover321** [htyjers/StrDiffusion#16]
Hello,
Thanks for the excellent open code. I face a problem with **[Places2] T=100** model extraction cipher.

**Comment by htyjers** [comment]
sorry, could you please provide more details, I can open it without cipher
<img width="1048" alt="1716361544835" src="https://github.com/htyjers/StrDiffusion/assets/97180052/dd3bd4d3-52fb-4b3b-b68f-8e0035b6239e">

**Comment by lzwRover321** [comment]
![image](https://github.com/htyjers/StrDiffusion/assets/38747253/03ea772c-3a64-461e-8f94-28d402ebe513)
I can't open it. Places2, T=400 I can open.

**Comment by htyjers** [comment]
链接：https://pan.baidu.com/s/1NHfmvfjk9H-bjw7nmBjwJQ?pwd=b2wn 
提取码：b2wn
**you can try this new link**

**Comment by lzwRover321** [comment]
> b46m
I can open it now, thank you!
