### ISSUE TITLE
代码运行问题

### ISSUE THREAD

**Issue by Migrant-workers-rmb** [htyjers/StrDiffusion#17]
作者你好，感谢您的分享！我对您的研究成果非常感兴趣，想要复现一下结果。请问您所提供的代码可以直接进行测试那一步吗，还是说要先经历三个部分的训练之后才能进行测试？

**Comment by Migrant-workers-rmb** [comment]
![Uploading QQ图片20240525124646.png…]()
这是我在加载了T=400权重后运行的结果，请问您是否知道为何会产生这样的错误呢？

**Comment by htyjers** [comment]
您好，直接测试就行，我这里无法加载您上传的图像

**Comment by Migrant-workers-rmb** [comment]
![QQ图片20240525124646](https://github.com/htyjers/StrDiffusion/assets/74965279/feb058cb-9215-441e-aaf1-09a59213a2cf)

**Comment by Migrant-workers-rmb** [comment]
非常感谢您的回复！在按照[Test-Strdiffusion]的步骤中修改了掩码路径和图像路径的情况，以及输入Places2，T=400预训练模型，设置对应的超参数的情况下，我遇到的问题如上图所示。有时也会报错“段错误，核心已转储”，请问您知道这是什么原因吗？
