### ISSUE TITLE
关于structure分支的测试

### ISSUE THREAD

**Issue by Fengxixiaom** [htyjers/StrDiffusion#18]
您好，对您优秀的工作非常感兴趣。有一个问题想问一下，就是我只训练structure分支，我该怎么测试呀？

**Comment by htyjers** [comment]
不好意思，图像修复的目标是修复texture信息，所以我们仅利用structure作为辅助信息，重点集中在测试texture，您可以参照 **https://github.com/Algolzw/image-restoration-sde** 这篇论文的代码，来编写structure的测试代码
