### ISSUE TITLE
train问题

### ISSUE THREAD

**Issue by maoqiuerer** [htyjers/StrDiffusion#19]
今天是6月9日，我发现trian的时候gpu并没有运行，这样可以吗？
![abb32d573055981a9bd5cee79db9bed](https://github.com/htyjers/StrDiffusion/assets/128476770/9346ccaf-22e3-4f6d-ad68-cd4981e9cda6)

![3b5b4dd321748602c5abc314e3e17dc](https://github.com/htyjers/StrDiffusion/assets/128476770/c621841e-57f9-439e-b4d6-699b224e51c4)

**Comment by htyjers** [comment]
好像不行啊，正常运行是会打印loss和epoch信息的
<img width="785" alt="1717920495234" src="https://github.com/htyjers/StrDiffusion/assets/97180052/379c6f44-9231-451d-8640-31dc103995cb">

**Comment by maoqiuerer** [comment]
我训练只能出现这三行，你知道是哪里出问题了吗

**Comment by htyjers** [comment]
如果您还没有解决这个问题，可以看下这篇blog,  这个问题的出现可能和集群的组织结构相关https://blog.csdn.net/lishanlu136/article/details/121143677

**Comment by maoqiuerer** [comment]
解决咯谢谢 是我的版本不太对






------------------ 原始邮件 ------------------
发件人: Haipeng Liu ***@***.***&gt;
发送时间: 2024年6月19日 12:28
收件人: htyjers/StrDiffusion ***@***.***&gt;
抄送: maoqiuerer ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [htyjers/StrDiffusion] train问题 (Issue #19)





 
如果您还没有解决这个问题，可以看下这篇blog,  这个问题的出现可能和集群的组织结构相关https://blog.csdn.net/lishanlu136/article/details/121143677
