### ISSUE TITLE
关于mask数据集的问题

### ISSUE THREAD

**Issue by stzyh** [htyjers/StrDiffusion#20]
您好！我对您优秀的工作感到十分赞赏，我想跟随您的工作，请问您可以公布您论文中用于测试的mask数据集作为我后续工作的参考吗？十分感谢

**Comment by htyjers** [comment]
感谢您的关注，我们使用的是最常用的mask数据集，您可以从[这里](https://nv-adlr.github.io/publication/partialconv-inpainting)下载
<img width="691" alt="1718426883092" src="https://github.com/htyjers/StrDiffusion/assets/97180052/7989d242-1450-4a2b-bd34-c6482190f06e">

其他像LAMA等工作也提出了相关的mask数据集，您后续工作可以按需求挑选
