### ISSUE TITLE
结果

### ISSUE THREAD

**Issue by LQ971225** [htyjers/StrDiffusion#21]
谢谢您如此好的文章！感谢您的耐心。
我想问一下作者跑出来的结果是results 
![2024-06-22 10-37-50屏幕截图](https://github.com/htyjers/StrDiffusion/assets/147681647/0300ee8d-8fba-4c37-bf7a-f651c973ee35)
里面的哪一种，我设置为epoch=100,bachsize=2,2700张自己的数据集，感觉结果不好，作者有什么建议呢，感谢您耐心的回答,谢谢

**Comment by htyjers** [comment]
<img width="644" alt="1719059709521" src="https://github.com/htyjers/StrDiffusion/assets/97180052/51515c95-9366-474b-82ce-6d9e23dee9d7">

您好，我截取了您提供的图片后，用places2参数测试，虽然不是同一个数据集，但结果应该不是特别差吧，根据您生成的图片，我猜是不是训练和测试时的步长T设置不一样啊

**Comment by LQ971225** [comment]
谢谢您耐心的回复，您说的是对的，我统一了步长T,并重新测试了，但结果不好，您对小数据集设置T有啥建议吗，您设置的bachsize是多少呢?谢谢您的回复

**Comment by htyjers** [comment]
我们论文中提到，需要增强structure与texture之间的相关性从而让structure更好的指导texture，较大的T(我建议可以设置T=200对于较小的数据集)可以让扩散过程更加细致，从而更好的保持二者之间的关联性。其次，我们采用的是较为通用的灰度图扩散到轮廓图作为structure信息，由于采集内容的不同，小数据集可能需要选择一些更契合数据集特性的信息作为structure。未来，我们正在解决如何进一步增强二者间关联度的问题，从而让指导更加有效，您可以继续关注我们的工作，谢谢。

**Comment by htyjers** [comment]
您也可以为小数据集修改[这里](https://github.com/htyjers/StrDiffusion/blob/772dd44b5595293d95efa5d92745ce48db185d66/test/texture/config/inpainting/utils/sde_utils.py#L295-L296)的参数来进行调整

**Comment by LQ971225** [comment]
谢谢您的回复，这几天我修改了T=200,和总的epoch,结果得到了提升，谢谢您，祝您生活愉快！

**Comment by LQ971225** [comment]
谢谢您的回复，这几天我修改了T=200,和总的epoch,结果得到了提升，但我发现在路径里放的掩码和输出最后results里面生成的masked(001_m)掩码不一样，若想和我输入的mask一样，我需要如何操作呢，非常感谢您，期待您的回复！祝您生活愉快！

**Comment by htyjers** [comment]
您的不一样是指是不同的mask被调取了，还是在同一个mask，图像发生了旋转，位移等操作，
如果是第一种，你可以检查下[这里](https://github.com/htyjers/StrDiffusion/blob/10f09dbdb2cd24b1ea3002552c98ca20186d592c/test/texture/config/inpainting/options/test/ir-sde.yml#L15),这里是输入mask地址的地方，可以查看mask数据集位置是否有误
如果是第二种，你可以检查下[这里](https://github.com/htyjers/StrDiffusion/blob/10f09dbdb2cd24b1ea3002552c98ca20186d592c/test/texture/config/inpainting/test.py#L202-L226)的代码，这里是调用mask的dataloader，你是否对mask进行了变换
