### ISSUE TITLE
有关输入数据通道数的问题

### ISSUE THREAD

**Issue by vfcerexwn** [htyjers/StrDiffusion#22]
您好，请问如果想处理灰度图，代码需要在哪里作出修改，谢谢！

**Comment by htyjers** [comment]
我没太明白您的意思，你是想在哪个分支处理灰度图，structure分支本身修复结果就是灰度图，texture分支是修复RGB图像的，您可以给出一些细节信息吗

**Comment by paco7er** [comment]
如果我想直接传入灰度图，该如何修改代码，
File "/autodl-fs/data/StrDiffusion/test/texture/config/inpainting/data/GT_dataset.py", line 128, in __getitem__
    if img_GT.shape[2] == 3:
IndexError: tuple index out of range
现在出现在了这个问题
