### ISSUE TITLE
Baidu cloud link

### ISSUE THREAD

**Issue by JEONG8652** [htyjers/StrDiffusion#23]
Hello, Thank you for your great work.

I would like to try your pretrained model.
but unfortunately, I am living outside china so I cannot download model weights from Baidu Cloud.
would you mind uploading the model weight to an another cloud service like google drive? 

Thank you.

**Comment by htyjers** [comment]
[Discriminator-[T=400]](https://drive.google.com/file/d/1GIgKH3qchD3HoCLx8tpKjG9MwlRJS1Vw/view?usp=sharing)
[Structure-[T=400]](https://drive.google.com/file/d/11NiB77Dsbqla2Wk05gzj8t0KfBK9F6rb/view?usp=sharing)
[Texture-[T=400]](https://drive.google.com/file/d/14ilwfzn3_KGAFJStvQqHqL4lBj8-NG9m/view?usp=sharing)
