### ISSUE TITLE
Google Drive Link

### ISSUE THREAD

**Issue by Vinayak-VG** [htyjers/StrDiffusion#24]
Please also add a google drive link for your pretrained models. It is very difficult to access the baidu link. Please do it as soon as possible. Thanks in advance

**Comment by htyjers** [comment]
[Discriminator-[T=400]](https://drive.google.com/file/d/1GIgKH3qchD3HoCLx8tpKjG9MwlRJS1Vw/view?usp=sharing)
[Structure-[T=400]](https://drive.google.com/file/d/11NiB77Dsbqla2Wk05gzj8t0KfBK9F6rb/view?usp=sharing)
[Texture-[T=400]](https://drive.google.com/file/d/14ilwfzn3_KGAFJStvQqHqL4lBj8-NG9m/view?usp=sharing)

**Comment by saloni1126** [comment]
![Screenshot 2024-11-18 111154](https://github.com/user-attachments/assets/66378365-0754-477a-ae88-50d26877d258)
the google drive is not accessible for our pretrained models .please provide an accessible link
