### ISSUE TITLE
能否测试不同分辨率的图像？

### ISSUE THREAD

**Issue by Chzhiyuan512** [htyjers/StrDiffusion#25]
在测试中发现只能测试256*256的图像，是否可以测试更高分辨率的图像（比如512*512）？如果可以应该怎么修改？

**Comment by htyjers** [comment]
Image 数据集修改[这里](https://github.com/htyjers/StrDiffusion/blob/10f09dbdb2cd24b1ea3002552c98ca20186d592c/test/texture/config/inpainting/data/GT_dataset.py#L118)
Mask 数据集修改[这里](https://github.com/htyjers/StrDiffusion/blob/10f09dbdb2cd24b1ea3002552c98ca20186d592c/test/texture/config/inpainting/test.py#L212-L216)
但由于我是按256分辨率训练的，所以想要测试更高分辨率的图像，最好在相应的图像上进行训练
