### ISSUE TITLE
paris streetview数据集

### ISSUE THREAD

**Issue by wangupupup** [htyjers/StrDiffusion#26]
作者您好！最近在学习你们的工作，请问可以提供paris streetview数据集在10%-20%、20%-30%、30%-40%、40%-50%的PSNR\ssim\fid指标吗？或者提供预训练模型我自己测试一下，想了解一下指标情况。

**Comment by htyjers** [comment]
已更新readme文件

**Comment by wangupupup** [comment]
Thank you very much！！！！
