### ISSUE TITLE
请教FID指标问题

### ISSUE THREAD

**Issue by wangupupup** [htyjers/StrDiffusion#28]
您好！我使用相同模型测量places2数据集在mask为10%-20%时修复出来的1000张和2000张图片的fid分别为11.1674、6.4077，感觉fid很不稳定。请问您怎么看待这个指标的不稳定性呢？StrDiffusion测places2数据集时采用了多少张测试集照片呢（我看places2本身测试集九万多张，实在太多了）？

**Comment by htyjers** [comment]
1. 你可以去研究下FID这个指标，它的数值大小是和测试图片的数量相关的，FID的计算依赖于生成样本与真实样本的统计分布。当样本数量较少时，统计分布可能不稳定，导致FID的波动较大。
2. 标准的places2的测试图片应该是36500张，麻烦您确认下载的图片是否是正确的。
3. 我们用了800张，你可以去看下以往的论文，大部分使用places2数据集的结果，基本上都是从测试集中随机挑选固定数量的图片进行测试，这个看FID的数值范围就能看出来了。

**Comment by wangupupup** [comment]
**谢谢您的建议和分享！！**
