### ISSUE TITLE
About the cuda version

### ISSUE THREAD

**Issue by Lanxin1011** [htyjers/StrDiffusion#3]
Dear the authors, thanks for your wonderful work! I'm curious about whether I could run your code under other CUDA versions, for example like CUDA 11.3 and CUDA 11.8?

Really looking forward to your reply!!!^^

**Comment by htyjers** [comment]
Thank you for your attention, I think the CUDA 11.3 or CUDA 11.8 can also well run my code. I just list the version of my environment.

**Comment by Lanxin1011** [comment]
Thanks for your prompt reply! I'll try it immediately : )
