### ISSUE TITLE
训练与测试的相关问题

### ISSUE THREAD

**Issue by everythingallrigh** [htyjers/StrDiffusion#32]
你好，非常感谢您开源的代码 
1、我想问一下 你们这个训练到论文的模型4卡2080ti大概跑了多久？
2、请问这个test测试的时候，在ir-sde中，mask数据集指的是LQ(退化后的图像)吗？
再次非常感谢，希望能得到您的回复。

**Comment by htyjers** [comment]
感谢关注：
1. 小规模数据集3-4天，大规模数据集至少半个月吧
2. mask+image组成的遮挡图片才是LQ
