### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by zf-666** [htyjers/StrDiffusion#33]
您好，
   想请问下如果要修改训练集的图像大小该修改什么地方呢。例如将256*256的输入改成480*640 。 
   以及模型似乎可以直接推理480*640分辨率的输入图片，但速度慢很多，这是为啥？
   
感谢！

**Comment by htyjers** [comment]
1. 以texture训练模型为例，您可以修改[link1](https://github.com/htyjers/StrDiffusion/blob/751b3297553ef140ea2f71c5b8347d98c1cf55c0/train/texture/config/inpainting/options/train/ir-sde.yml#L27)和[link2](https://github.com/htyjers/StrDiffusion/blob/751b3297553ef140ea2f71c5b8347d98c1cf55c0/train/texture/config/inpainting/train.py#L295)
2. 因为分辨率变大了，u-net网络要处理的数据量更大，所以会变慢很多

**Comment by zf-666** [comment]
感谢您的回复，希望可以提供一下多卡训练的代码。谢谢！

**Comment by zf-666** [comment]
我的问题已解决， 由于pytorch的版本问题导致 --local-rank , --local_rank 写法不一致
python -m torch.distributed.launch --nproc_per_node=2 --master_port=6512 train.py -opt=options/train/ir-sde.yml --launcher pytorch
