### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by robot444** [htyjers/StrDiffusion#34]
您好，我在训练过程中遇到了一些问题：3个模型权重的训练顺序是按照您在readme中写的那样依次训练吗，以及训练3个权重文件时候是否只需要加载当前的预训练权重一个文件，存在疑惑（因为3个相关训练代码中都是加载G和Gs），谢谢您的解答

**Comment by htyjers** [comment]
按照readme文件中的顺序依次训练即可，每个模块都是单独训练，不需要加载预训练权重文件，只有在测试时，才会同时加载3个预训练文件
