### ISSUE TITLE
模型训练

### ISSUE THREAD

**Issue by robot444** [htyjers/StrDiffusion#36]
您好，感谢您之前的绝大，我在训练3部分网络代码发现denoising_model.py部分都需要加载
def load(self):
        load_path_G = self.opt["path"]["pretrain_model_G"]
        load_path_Gs = self.opt["path"]["pretrain_model_Gs"]
        if load_path_G is not None:
            logger.info("Loading model for G [{:s}] ...".format(load_path_G))
            self.load_network(load_path_G, self.model, self.opt["path"]["strict_load"])
            self.load_network(load_path_Gs, self.models, self.opt["path"]["strict_load"])
请问如果重新训练是否不需要动这部分代码，以及在后续Texture Denoising Model和Discriminator Network的训练中是否需要加载之前训练好的其它网络，这三个模型之前的训练是完全独立互不干扰的吗，感谢解答

**Comment by htyjers** [comment]
这部分代码不用动，这3个模型在训练中是互不干扰的，您可以看到虽然函数进行了调用，但是其中有个条件是--[if load_path_G is not None](https://github.com/htyjers/StrDiffusion/blob/751b3297553ef140ea2f71c5b8347d98c1cf55c0/train/structure/config/inpainting/models/denoising_model.py#L266)，而这个值在训练中设置的是[None](https://github.com/htyjers/StrDiffusion/blob/751b3297553ef140ea2f71c5b8347d98c1cf55c0/train/structure/config/inpainting/options/train/ir-sde.yml#L44)

我为了便于读者使用代码，我特意将训练模块的代码分成了3个独立模块，所以您按照readme文件里面的步骤，主要是对数据集路径进行相应的替换即可应用到您自己的训练集上面，
