### ISSUE TITLE
请教一下关于公式(11)和训练过程的代码问题

### ISSUE THREAD

**Issue by CZY-Code** [htyjers/StrDiffusion#38]
(1) 代码中没有用到公式(11)的代码实现，求y_{t-1}的最优解？
(2) 三个网络是分开训练的吗？没有使用训练好的structure去噪网络辅助训练texture去噪网络？

**Comment by htyjers** [comment]
1. 我们用structure作为辅助去指导texture信息的恢复，从而可以更加合理的去学习原始去噪目标（公式4）。我们认为在由于有了structure作为条件加入texture的去噪网络后，原始的优化目标已经发生了改变，即为公式11
2. 为了更好的优化模型与降低资源消耗，我们选择了分开训练3个网络，

**Comment by CZY-Code** [comment]
谢谢
