### ISSUE TITLE
CUDA VISIBLE DEVICES=0

### ISSUE THREAD

**Issue by maoqiuerer** [htyjers/StrDiffusion#4]
![6971629fa112e7c01ea13c8781cd8c3](https://github.com/htyjers/StrDiffusion/assets/128476770/14c0b947-51d3-462c-8c24-845c509873c9)
I run python3 ./train/structure/config/inpainting/train.py， but it happened it. what should i do?

**Comment by htyjers** [comment]
Under "train" folder, it has created the "experiments" folder, you can find the training log in this folder

**Comment by maoqiuerer** [comment]
I've been training on cosine schedule for a day now and it's not finished yet

**Comment by htyjers** [comment]
1. you can set the proper [niter](https://github.com/htyjers/StrDiffusion/blob/dc2efa828d47af3b12fbd13d0cec850be3fad36e/train/structure/config/inpainting/options/train/ir-sde.yml#L55-L57) for your dataset, I set the parameters for the Places2 dataset.
2. the pretrained models have saved in the **./train/experiments/inpainting/models** even not finish training, you can now download for testing.
