### ISSUE TITLE
您好，使用您的三个训练后，进行测试，但输出严重伪影

### ISSUE THREAD

**Issue by krantbrity** [htyjers/StrDiffusion#40]

**Comment by krantbrity** [comment]
![qr](https://github.com/user-attachments/assets/e9aecf3a-b264-4e91-b03d-559a876c0aa8)

**Comment by krantbrity** [comment]
请问您能分析一下这是什么原因吗，还是我有哪一步需要调整

**Comment by htyjers** [comment]
![image](https://github.com/user-attachments/assets/73b0b627-5ac4-4b3c-914f-e7d807e147c5)
您好，根据您提供的二维码图像修复任务，由于您提供的二维码只有黑白2种颜色，对二维码图像分为结构structure和texture语义信息并没有太大的意义，我推荐您只采用我们单独的structure模型就可以进行较好的修复了，因为structure更偏向于物体结构信息的修复，如下图所示，我只利用structure网络就已经可以取得较好的结构，如果进一步利用texture网络，反而会造成干扰。
<img width="599" alt="1723108397078" src="https://github.com/user-attachments/assets/72c8a79b-cbff-4482-b700-bbb7fea5a6b2">
其次，我利用places预训练模型进行了测试，如果加入语义或者颜色，此时，加入texture信息到二维码图像修复任务中应该能发挥一定的作用，如下图所示
<img width="453" alt="1723108878119" src="https://github.com/user-attachments/assets/11d4e0e9-c0b2-42d9-ab22-24fd846b2286">
<img width="459" alt="1723109216055" src="https://github.com/user-attachments/assets/1e3dc421-8ea7-46ad-924b-77608bfe4ba5">

**Comment by krantbrity** [comment]
非常感谢您详细的回复！不胜感激，但是我使用了另外的数据集，发现仍然存在修复不了的情况，是否会与数据集大小有关系，我的训练集、测试集和验证集分别为2722、840和980

**Comment by krantbrity** [comment]
![1](https://github.com/user-attachments/assets/6c49afca-a985-4587-a4b0-d59edc54c440)

**Comment by krantbrity** [comment]
问题有可能是出在StrDiffusion-main/train/texture/config/inpainting/data/GT_dataset.py 中：      
 # get GT image
        GT_path = self.GT_paths[index]
        if self.opt["data_type"] == "lmdb":
            resolution = [int(s) for s in self.GT_sizes[index].split("_")]
        else:
            resolution = None
        img_GT = util.read_img(
            self.GT_env, GT_path, resolution
        )  # return: Numpy float32, HWC, BGR, [0,1]

        if self.opt["phase"] == "train":
            H, W, C = img_GT.shape

            rnd_h = random.randint(0, max(0, H - GT_size))
            rnd_w = random.randint(0, max(0, W - GT_size))
            img_GT = img_GT[rnd_h : rnd_h + GT_size, rnd_w : rnd_w + GT_size, :]
            img_GT = cv2.resize(img_GT, (GT_size, GT_size), interpolation=cv2.INTER_AREA)
我最后加的这句img_GT = cv2.resize(img_GT, (GT_size, GT_size), interpolation=cv2.INTER_AREA)上吗

**Comment by htyjers** [comment]
1. 数据集应该是太小了，图像修复常用的最小数据集PSV，训练集也有14900张图片
2. 在[这里](https://github.com/htyjers/StrDiffusion/blob/751b3297553ef140ea2f71c5b8347d98c1cf55c0/train/texture/config/inpainting/options/train/ir-sde.yml#L27)就可以设置图像的大小，img_GT = cv2.resize(img_GT, (GT_size, GT_size), interpolation=cv2.INTER_AREA)这句话我感觉好像没有必要加上

**Comment by krantbrity** [comment]
感谢您的指导，我再用足够数量的训练集试一试

**Comment by wwzh2626** [comment]
> ![image](https://github.com/user-attachments/assets/73b0b627-5ac4-4b3c-914f-e7d807e147c5) 您好，根据您提供的二维码图像修复任务，由于您提供的二维码只有黑白2种颜色，对二维码图像分为结构structure和texture语义信息并没有太大的意义，我推荐您只采用我们单独的structure模型就可以进行较好的修复了，因为structure更偏向于物体结构信息的修复，如下图所示，我只利用structure网络就已经可以取得较好的结构，如果进一步利用texture网络，反而会造成干扰。 <img alt="1723108397078" width="599" src="https://private-user-images.githubusercontent.com/97180052/356158760-72c8a79b-cbff-4482-b700-bbb7fea5a6b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI5Nzc4NjcsIm5iZiI6MTc0Mjk3NzU2NywicGF0aCI6Ii85NzE4MDA1Mi8zNTYxNTg3NjAtNzJjOGE3OWItY2JmZi00NDgyLWI3MDAtYmJiN2ZlYTVhNmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI2VDA4MjYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NGEyNmEzNWViNzFlMjEwZjFlZDllYTBjMzFhMDUzMzk0OWQ0MmRiOWM2OWI4NmQ4MmVlZGE0NGJhNjQ1OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0x1jRiQHbJbDr01-4iBojHTQT549plUIIDn9NKPawbg"> 其次，我利用places预训练模型进行了测试，如果加入语义或者颜色，此时，加入texture信息到二维码图像修复任务中应该能发挥一定的作用，如下图所示 <img alt="1723108878119" width="453" src="https://private-user-images.githubusercontent.com/97180052/356162714-11d4e0e9-c0b2-42d9-ab22-24fd846b2286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI5Nzc4NjcsIm5iZiI6MTc0Mjk3NzU2NywicGF0aCI6Ii85NzE4MDA1Mi8zNTYxNjI3MTQtMTFkNGUwZTktYzBiMi00MmQ5LWFiMjItMjRmZDg0NmIyMjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI2VDA4MjYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMDYzNzZmN2Q0NzBjNDZlNzIxZmUwODhhODk3ODA3MzRmNGU4OGM3ODE1MDY0OTFjYzhhMGExMWEyM2MzYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BwkbS1vRL-LsyRNElWPkwesFjJEa1Txp-55wUraAUJ0"> <img alt="1723109216055" width="459" src="https://private-user-images.githubusercontent.com/97180052/356163434-1e3dc421-8ea7-46ad-924b-77608bfe4ba5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI5Nzc4NjcsIm5iZiI6MTc0Mjk3NzU2NywicGF0aCI6Ii85NzE4MDA1Mi8zNTYxNjM0MzQtMWUzZGM0MjEtOGVhNy00NmFkLTkyNGItNzc2MDhiZmU0YmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI2VDA4MjYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNThlOWVjNGI5ZWE4MTAyMTBhODZjM2Q5MjIyYjhjM2JmMjY2MTI1YWQxZDcyNDk5MmE3NjU3MTQ4ZWM5OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FA7ZIoZBWaV5jfB7J-qHDuSj2dCToNbsgVn8vC6SBZA">



> ![image](https://github.com/user-attachments/assets/73b0b627-5ac4-4b3c-914f-e7d807e147c5) 您好，根据您提供的二维码图像修复任务，由于您提供的二维码只有黑白2种颜色，对二维码图像分为结构structure和texture语义信息并没有太大的意义，我推荐您只采用我们单独的structure模型就可以进行较好的修复了，因为structure更偏向于物体结构信息的修复，如下图所示，我只利用structure网络就已经可以取得较好的结构，如果进一步利用texture网络，反而会造成干扰。 <img alt="1723108397078" width="599" src="https://private-user-images.githubusercontent.com/97180052/356158760-72c8a79b-cbff-4482-b700-bbb7fea5a6b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI5Nzk1MjgsIm5iZiI6MTc0Mjk3OTIyOCwicGF0aCI6Ii85NzE4MDA1Mi8zNTYxNTg3NjAtNzJjOGE3OWItY2JmZi00NDgyLWI3MDAtYmJiN2ZlYTVhNmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI2VDA4NTM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzZjk5MDMyN2U2YjVjYzA3YWI3MDEyYzZkYzE0Y2UxYmJkZTEwY2FlZDgyZGYwYjA4MzNkYzg3NTE3NGQ1MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L-PuoTT_xyrJXARELuFr0zhceq8N8D1nIXhGAL2eRtI"> 其次，我利用places预训练模型进行了测试，如果加入语义或者颜色，此时，加入texture信息到二维码图像修复任务中应该能发挥一定的作用，如下图所示 <img alt="1723108878119" width="453" src="https://private-user-images.githubusercontent.com/97180052/356162714-11d4e0e9-c0b2-42d9-ab22-24fd846b2286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI5Nzk1MjgsIm5iZiI6MTc0Mjk3OTIyOCwicGF0aCI6Ii85NzE4MDA1Mi8zNTYxNjI3MTQtMTFkNGUwZTktYzBiMi00MmQ5LWFiMjItMjRmZDg0NmIyMjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI2VDA4NTM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYTZjM2YzN2U4YWUyNjU4MDM2NGYzOWFmMTA3MGE5NmFmMzY4OTRjNDcyMDJlNmVjNDk4ZmQ0MDMxOTdhYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-V464wt96jy6qeEQcGzuA_bH9ZXOD6AiTPuBsod-J2E"> <img alt="1723109216055" width="459" src="https://private-user-images.githubusercontent.com/97180052/356163434-1e3dc421-8ea7-46ad-924b-77608bfe4ba5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI5Nzk1MjgsIm5iZiI6MTc0Mjk3OTIyOCwicGF0aCI6Ii85NzE4MDA1Mi8zNTYxNjM0MzQtMWUzZGM0MjEtOGVhNy00NmFkLTkyNGItNzc2MDhiZmU0YmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI2VDA4NTM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0N2QzZWU4MjVkYWJhMTE2NTFlMjUxMTk1Y2Q2YTlhOWZlYTMzYjQ0MGFlMDk1MmEyYmI1YWFkMTkwZWJhMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4MEgzOwVRoPXmw53uq79vA-9FJUavZyHsshL_1wvZUc">

作者您好 请问要如何单独仅采用structure模型进行推理， 我在test时出现了bug。是在model.test时出现的问题。请问要如何才能实现单独使用structure模型单独推理？

**Comment by krantbrity** [comment]
> > 感谢您的指导，我再用足够数量的训练集试一试
> 
> May I ask if you continued with this work? I trained using 30,000 images sized 256×256, and convergence occurred quickly (within 1–2 epochs). However, the code provided by the author includes 8,000,000 iterations. Even when using 180,000 images (approximately 750 epochs), I find this unbelievable. Did you encounter such an issue in your work? Should training continue after convergence?

其实我后来也没尝试了，这个方向太卷了，跑路了hhh
