### ISSUE TITLE
CelebA数据集模型权重

### ISSUE THREAD

**Issue by YouXMu** [htyjers/StrDiffusion#42]
您好，我发现您没有上传人脸数据集下的模型相关权重，您能上传一下吗？因为我又重新训练了一下纹理去噪网络，所以我想用下您训练好的结构去噪网络和判别器来测试一下纹理网络。

**Comment by 007-001** [comment]
你好 @YouXMu  ，希望没有打扰到你，我最近非常需要StrDiffusion的人脸数据集权重文件和PSV，T=100的权重文件，但是原作者上传的文件已经过期了，我看了您的评论感觉你应该已经下载过该文件了，如果你有空的话吗，可以给我发一下嘛，谢谢
