### ISSUE TITLE
救救孩子吧，代码运行到输出数据长度之后，就一直没有反应了，好像都没有在服务器上跑，不占内存

### ISSUE THREAD

**Issue by liuna0211** [htyjers/StrDiffusion#45]
![image](https://github.com/user-attachments/assets/9065f5d3-e0b4-44a2-9558-88f28ad516a8)

**Comment by htyjers** [comment]
可以参考下这篇[blog](https://blog.csdn.net/lishanlu136/article/details/121143677), 代码有一部分是调用C语言程序进行加速计算的，当程序不正常结束时，本地GPU集群可能无法清除相关的lock文件
