### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by zhangshilong2000** [htyjers/StrDiffusion#5]
您好，在运行train.py时出现该错误，这个问题可能是由于什么导致的？
![image](https://github.com/htyjers/StrDiffusion/assets/72057128/028104ac-e306-41f3-a161-70c40d0db8dc)

**Comment by htyjers** [comment]
Thank you for your attention, 🙏🙏🙏 I am sorry for this error, when I organize my code for github, I am missing to delete some redundant code, I have updated the code. You can just delete the import of [**MatchingLoss1**](https://github.com/htyjers/StrDiffusion/blob/192dc1722081416399067baa9c9e3d0836639d38/train/texture/config/inpainting/models/denoising_model.py#L19) in the [_denoising_model.py_](https://github.com/htyjers/StrDiffusion/blob/main/train/texture/config/inpainting/models/denoising_model.py) .

**Comment by zhangshilong2000** [comment]
感谢您的及时回复！祝您生活愉快


张世龙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "htyjers/StrDiffusion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月14日(星期天) 下午5:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [htyjers/StrDiffusion] 运行错误 (Issue #5)





 
Thank you for your attention, 🙏🙏🙏 I am sorry for this error, when I organize my code for github, I am missing to delete some redundant code, I have updated the code. You can just delete the import of MatchingLoss1 in the denoising_model.py .
