### ISSUE TITLE
微调

### ISSUE THREAD

**Issue by wangupupup** [htyjers/StrDiffusion#52]
您好！请问如何基于已有的places2模型在另外一个小数据集上微调呢

**Comment by htyjers** [comment]
Hello! My project doesn't contain any fine-tuning code, but this implementation is based on [Image Restoration SDE](https://github.com/Algolzw/image-restoration-sde). You can check this repository to see if it includes any fine-tuning code for reference.

**Comment by wangupupup** [comment]
好嘞 谢谢
