### ISSUE TITLE
About [Places2] T=100 model 

### ISSUE THREAD

**Issue by YouXMu** [htyjers/StrDiffusion#54]
Hello,
Thanks for the excellent open code. I noticed that you conducted the comparison experiments in the T=100 setting in the paper , so I would like to use the model in this setting to compare with my method, but I wasn't able to find the pre-training weights corresponding to places2 in T=100, and the training in T=400 is too long for me due to computational consumption considerations, could you share the weights of the model in T=100?  Looking forward to your reply soon!

**Comment by htyjers** [comment]
you can download in [here](https://pan.baidu.com/s/1cmVl8IAfJfJkUb9qxknmtw?pwd=htyj),  you can considering set 

Places2 -- T=100, u_max = 10, u_min = 2, jump = 1, re = 2 

for saving time.

https://github.com/htyjers/StrDiffusion/blob/751b3297553ef140ea2f71c5b8347d98c1cf55c0/test/texture/config/inpainting/utils/sde_utils.py#L296


Last but not least, For Places2 dataset, 
I was on 256x256 image slices extracted from 512x512 images, similar to the LaMa approach. Below is the relevant code you should change in this version. https://github.com/htyjers/StrDiffusion/blob/751b3297553ef140ea2f71c5b8347d98c1cf55c0/test/texture/config/inpainting/data/GT_dataset.py#L117-L119

H, W, C = img_GT.shape
GT_size = 256
rnd_h = random.randint(0, max(0, H - GT_size))
rnd_w = random.randint(0, max(0, W - GT_size))
img_GT = img_GT[rnd_h : rnd_h + GT_size, rnd_w : rnd_w + GT_size, :]

**Comment by YouXMu** [comment]
thank you very much！
