### ISSUE TITLE
DATASET

### ISSUE THREAD

**Issue by zhangshilong2000** [htyjers/StrDiffusion#6]
您好，我想知道，Train-[Structure Denoising Model]，Train-[Texture Denoising Model]，Train-[Discriminator Network]这三个部分的训练是采用相同情况数据集的吗？不需要将其处理为灰度图吗？

**Comment by htyjers** [comment]
使用相同的数据集即可训练，我已经在代码中对RGB图像进行了处理，会自动转化为灰度图和edge map.

**Comment by HORIZON0122** [comment]
How to download mask and image datasets

**Comment by htyjers** [comment]
> How to download mask and image datasets

Thank you for your attention, you can download the image dataset Places2 at [here](http://places2.csail.mit.edu/download.html), the irregular mask dataset at [here](https://nv-adlr.github.io/publication/partialconv-inpainting).

**Comment by ZhaoshuoYang** [comment]
![image](https://github.com/htyjers/StrDiffusion/assets/125345493/bf1e855b-5db6-47ef-a404-003eeba30db6)

In train/structure/config/inpainting/train.py, line 56, trian->train

**Comment by htyjers** [comment]
> ![image](https://private-user-images.githubusercontent.com/125345493/322774729-bf1e855b-5db6-47ef-a404-003eeba30db6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTgwOTYsIm5iZiI6MTcxMzI1Nzc5NiwicGF0aCI6Ii8xMjUzNDU0OTMvMzIyNzc0NzI5LWJmMWU4NTViLTVkYjYtNDdlZi1hNDA0LTAwM2VlYmEzMGRiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQwODU2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDQ2NDQwNjhlNTQ0ZTMwMWJiYTgyOGU0ZThjMmIxOWYxMTVhZjhlMTc4NDcxODI2MDY5MTEyMmYyMTFjOGQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xwuz53f8oWFNE3Ch9TlhGHzkHsp_Ga7gYpAf2LlwZWk)
> 
> In train/structure/config/inpainting/train.py, line 56, trian->train

thank you very much

**Comment by zhangshilong2000** [comment]
你好，我在测试过程中遇到如下问题，这可能是由于什么引起的？![image](https://github.com/htyjers/StrDiffusion/assets/72057128/43b1453f-af1f-4103-9f6b-8bd6ef04002c)
